apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{- if .Values.tls }}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
{{- end }}
{{- if .Values.ingressAnnotations }}
{{ toYaml .Values.ingressAnnotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.tls }}
  tls:
  - hosts:
    - "{{ .Values.subdomain }}.{{ .Values.domain }}"
    secretName: "{{ .Values.subdomain }}-{{ .Values.domain }}-tls"
{{- end }}
  rules:
  - host: "{{ .Values.subdomain }}.{{ .Values.domain }}"
    http:
      paths:
      - path: {{ .Values.domainPath }}
        backend:
          serviceName: {{ .Values.name }}
          servicePort: 80
