apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
{{- if .Values.serviceLabels }}
  labels:
{{ toYaml .Values.serviceLabels | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.servicePort }}
  selector:
    app: "{{ .Values.name }}-selector"
